pose_1:
  translation:
    x: 0.0
    y: 0.0
    z: 0.1
  rotation:
    x: 1.57079632679
    y: 0.0
    z: 0.0

pose_2:
  translation:
    x: 0.0
    y: 0.0
    z: 0.1
  rotation:
    x: 0.0
    y: 0.0
    z: -1.57079632679

pose_3:
  translation:
    x: 0.0
    y: 0.0
    z: 0.1
  rotation:
    x: 0
    y: 1.57079632679
    z: 0.0

pose_4:
  translation:
    x: 0.0
    y: 0.05
    z: 0.1
  rotation:
    x: 0
    y: 1.57079632679
    z: 0.0
